### ISSUE TITLE
谢谢分享，发现一个小bug

### ISSUE THREAD

**Issue by walijoy** [efeencheung/dmbase#1]
composer install的末尾，安装完所有的文件后，程序自动询问配置数据库安全字符串等信息

> Creating the "app/config/parameters.yml" file
> Some parameters are missing. Please provide them.
> database_host (127.0.0.1): 
> database_port (null): 
> database_name (symfony): dmbase  
> database_user (root): 
> database_password (null): root
> mailer_transport (smtp): 
> mailer_host (127.0.0.1): 
> mailer_user (null): 
> mailer_password (null): 
> secret (ThisTokenIsNotSoSecretChangeIt): 

然后程序会自动运行：

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

报如下错误

> [Doctrine\DBAL\Exception\ConnectionException]  
>   An exception occured in driver: SQLSTATE[HY000] [1049] Unknown database 'dmbase'  
> 
>   [Doctrine\DBAL\Driver\PDOException]  
>   SQLSTATE[HY000] [1049] Unknown database 'dmbase'  
> 
>   [PDOException]  
>   SQLSTATE[HY000] [1049] Unknown database 'dmbase' 

此后执行任意命令都会得到如上错误
比如执行

> php app/console doctrine:database:create 
> php app/console

命令等

**Comment by walijoy** [comment]
我在mysql里面手动建立dmbase后，再次执行 app/console脚本，得到如下错误

> [Doctrine\DBAL\Exception\TableNotFoundException]  
>   An exception occurred while executing 'SELECT \* FROM access_control':  
>   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dmbase.access_control' doesn't exist

**Comment by efeencheung** [comment]
恩 先更新一下，后面这个是你得执行创建数据表

**Comment by walijoy** [comment]
更新后得到一个致命错误
水平太弱，看38那行代码没看出任何问题

> Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception
> 
>   [RuntimeException]  
>   An error occurred when executing the "'cache:clear --no-warmup'" command:  
>   Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Call to a member  
>   function fetchAll() on boolean in /Applications/XAMPP/xamppfiles/htdocs/dmbase/src/Dm/Bundle/SecurityBundle  
>   /DependencyInjection/Compiler/AddSecurityPass.php:38  
>   Stack trace:  
>   #0 /Applications/XAMPP/xamppfiles/htdocs/dmbase/vendor/symfony/symfony/src/Symfony/Component/DependencyInje  
>   ction/Compiler/Compiler.php(107): Dm\Bundle\SecurityBundle\DependencyInjection\Compiler\AddSecurityPass->pr  
>   ocess(Object(Symfony\Component\DependencyInjection\ContainerBuilder))  
>   #1 /Applications/XAMPP/xamppfiles/htdocs/dmbase/vendor/symfony/symfony/src/Symfony/Component/DependencyInje  
>   ction/ContainerBuilder.php(574): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Sy  
>   mfony\Component\DependencyInjection\ContainerBuilder))  
>   #2 /Applications/XAMPP/xamppfiles/htdocs/dmbase/app/bootstrap.php.cache(2644): Symfony\Component\Dependency  
>   Injection\ContainerBuilder->compile()  
>   #3 /Applications/XAMPP/xamppfiles/htdocs/dmbase/app/bootstr in /Applications/XAMPP/xamppfiles/htdocs/dmbase  
>   /src/Dm/Bundle/SecurityBundle/DependencyInjection/Compiler/AddSecurityPass.php on line 38
