### ISSUE TITLE
创建数据表的时候报错，不知道 什么 原因 

### ISSUE THREAD

**Issue by caohui123** [efeencheung/dmbase#2]
![image](https://user-images.githubusercontent.com/10387629/32133018-c1810e1c-bc01-11e7-9219-563ea08436fd.png)

**Comment by efeencheung** [comment]
这个项目不维护了，过段时间会发布基于symfony3.3版本的新版本，解决这个问题需要你进入到
vendor/efeencheung/dm-admin-bundle/Entity 下，删除所有的Entity文件即可正常使用
